page_title: LSDB Builds
copier_project: lincc-frameworks/python-project-template

repos: 
  # Blocked by https://github.com/astronomy-commons/data.lsdb.io/issues/133
  # - repo: data.lsdb.io
  #   owner: astronomy-commons
  #   other_workflows:
  #     - connectivity-checks.yml

  - repo: hats
    owner: astronomy-commons
    smoke-test: smoke-test.yml
    benchmarks: asv-nightly.yml
    live-build: testing-and-coverage.yml

  - repo: hats-cloudtests
    owner: astronomy-commons
    smoke-test: smoke-test.yml
    benchmarks: asv-nightly.yml
    live-build: testing-and-coverage.yml

  - repo: hats-import
    owner: astronomy-commons
    smoke-test: smoke-test.yml
    live-build: testing-and-coverage.yml

  - repo: lsdb
    owner: astronomy-commons
    smoke-test: smoke-test.yml
    benchmarks: asv-nightly.yml
    live-build: testing-and-coverage.yml

  - repo: lsdb-crossmatch
    owner: astronomy-commons
    smoke-test: smoke-test.yml
    live-build: testing-and-coverage.yml

  - repo: lsdb-rubin
    owner: astronomy-commons
    smoke-test: smoke-test.yml
    live-build: testing-and-coverage.yml
    benchmarks: asv-nightly.yml
    other_workflows: 
      - smoke_test_conda.yml

  - repo: nested-pandas
    owner: lincc-frameworks
    smoke-test: smoke-test.yml
    benchmarks: asv-nightly.yml
    live-build: testing-and-coverage.yml

extra_links: 
  - text: LINCC Frameworks Dash
    url: https://lincc-frameworks.github.io/lf-workflow-dash/