page_title: RAIL Workflow Dashboard

repos:
  - repo: rail
    owner: lsstdesc
    smoke-test: smoke-test.yml
    build-docs: build_documentation.yml
    live-build: testing-and-coverage.yml
  
  - repo: rail_astro_tools
    owner: lsstdesc
    smoke-test: smoke-test.yml
    live-build: testing-and-coverage.yml
  
  - repo: rail_base
    owner: lsstdesc
    smoke-test: smoke-test.yml
    live-build: testing-and-coverage.yml
  
  - repo: rail_bpz
    owner: lsstdesc
    smoke-test: smoke-test.yml
    live-build: testing-and-coverage.yml
  
  - repo: rail_cmnn
    owner: lsstdesc
    smoke-test: smoke-test.yml
    live-build: testing-and-coverage.yml
  
  - repo: rail_delight
    owner: lsstdesc
    smoke-test: smoke-test.yml
    live-build: testing-and-coverage.yml
  
  - repo: rail_dsps
    owner: lsstdesc
    smoke-test: smoke-test.yml
    live-build: testing-and-coverage.yml
  
  - repo: rail_flexzboost
    owner: lsstdesc
    smoke-test: smoke-test.yml
    live-build: testing-and-coverage.yml
  
  - repo: rail_fsps
    owner: lsstdesc
    smoke-test: smoke-test.yml
    live-build: testing-and-coverage.yml
  
  - repo: rail_gpz_v1
    owner: lsstdesc
    smoke-test: smoke-test.yml
    live-build: testing-and-coverage.yml
  
  - repo: rail_lib_gp_comp
    owner: lsstdesc
    smoke-test: smoke-test.yml
    live-build: testing-and-coverage.yml
      
  - repo: rail_notebooks
    owner: OliviaLynn
    build-docs: render-notebooks.yml
  
  - repo: rail_pipelines
    owner: lsstdesc
    smoke-test: smoke-test.yml
    live-build: testing-and-coverage.yml
  
  - repo: RAIL-project-template
    owner: lsstdesc
    live-build: ci.yml
  
  - repo: rail_pzflow
    owner: lsstdesc
    smoke-test: smoke-test.yml
    live-build: testing-and-coverage.yml
  
  - repo: rail_sklearn
    owner: lsstdesc
    smoke-test: smoke-test.yml
    live-build: testing-and-coverage.yml
  
  - repo: rail_som
    owner: lsstdesc
    smoke-test: smoke-test.yml
    live-build: testing-and-coverage.yml
  
  - repo: tables_io
    owner: lsstdesc
    smoke-test: smoke-test.yml
    live-build: testing-and-coverage.yml
